{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-03-31T14:43:26.326187Z",
     "start_time": "2018-03-31T14:43:23.996151Z"
    }
   },
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "import numpy as np\n",
    "\n",
    "sys.path.append('E:/xinlib')\n",
    "import xin \n",
    "\n",
    "\n",
    "root = 'E:/Data/datasets/flower_photos/'\n",
    "dataset = xin.Path2Dataset(root).path2data()\n",
    "\n",
    "data, labels_idx = dataset\n",
    "labels = labels_idx.codes\n",
    "data_iter = xin.data_iter(data, labels, 32)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "start_time": "2018-03-31T14:43:26.038Z"
    },
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "for X, Y in data_iter:\n",
    "    X.dtype = np.uint8\n",
    "    break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-03-30T14:44:39.046147Z",
     "start_time": "2018-03-30T14:44:34.559100Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Anaconda3\\lib\\site-packages\\h5py\\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n"
     ]
    }
   ],
   "source": [
    "import io\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import PIL\n",
    "import tensorflow as tf\n",
    "def visualize_labeled_images(images, labels, max_outputs=3, name='image'):\n",
    "    def _visualize_image(image, label):\n",
    "        # Do the actual drawing in python\n",
    "        fig = plt.figure(figsize=(3, 3), dpi=80)\n",
    "        ax = fig.add_subplot(111)\n",
    "        ax.imshow(image[::-1,...])\n",
    "        ax.text(0, 0, str(label), \n",
    "          horizontalalignment='left', \n",
    "          verticalalignment='top')\n",
    "        fig.canvas.draw()\n",
    "        # Write the plot as a memory file.\n",
    "        buf = io.BytesIO()\n",
    "        data = fig.savefig(buf, format='png')\n",
    "        buf.seek(0)      \n",
    "        # Read the image and convert to numpy array\n",
    "        img = PIL.Image.open(buf)\n",
    "        return np.array(img.getdata()).reshape(img.size[0], img.size[1], -1)\n",
    "    def _visualize_images(images, labels):\n",
    "        # Only display the given number of examples in the batch\n",
    "        outputs = []\n",
    "        for i in range(max_outputs):\n",
    "            output = _visualize_image(images[i], labels[i])\n",
    "            outputs.append(output)\n",
    "        return np.array(outputs, dtype=np.uint8)\n",
    "    # Run the python op.\n",
    "    figs = tf.py_func(_visualize_images, [images, labels], tf.uint8)\n",
    "    return tf.summary.image(name, figs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-03-30T14:44:41.435768Z",
     "start_time": "2018-03-30T14:44:39.063098Z"
    }
   },
   "outputs": [
    {
     "ename": "InvalidArgumentError",
     "evalue": "TypeError: Invalid dimensions for image data\nTraceback (most recent call last):\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 157, in __call__\n    ret = func(*args)\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 27, in _visualize_images\n    output = _visualize_image(images[i], labels[i])\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 11, in _visualize_image\n    ax.imshow(image[::-1,...])\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\__init__.py\", line 1855, in inner\n    return func(ax, *args, **kwargs)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\axes\\_axes.py\", line 5487, in imshow\n    im.set_data(X)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 653, in set_data\n    raise TypeError(\"Invalid dimensions for image data\")\n\nTypeError: Invalid dimensions for image data\n\n\n\t [[Node: PyFunc = PyFunc[Tin=[DT_UINT8, DT_FLOAT], Tout=[DT_UINT8], token=\"pyfunc_0\", _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](PyFunc/input_0, PyFunc/input_1)]]\n\nCaused by op 'PyFunc', defined at:\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n    app.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 478, in start\n    self.io_loop.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 177, in start\n    super(ZMQIOLoop, self).start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 888, in start\n    handler_func(fd_obj, events)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n    self._handle_recv()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n    callback(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 283, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 233, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 399, in execute_request\n    user_expressions, allow_stdin)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 208, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 537, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2728, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2850, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2910, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-8-70455aae5562>\", line 1, in <module>\n    a = visualize_labeled_images(X, Y)\n  File \"<ipython-input-7-77ba72cfe590>\", line 31, in visualize_labeled_images\n    figs = tf.py_func(_visualize_images, [images, labels], tf.uint8)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 340, in py_func\n    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 241, in _internal_py_func\n    input=inp, token=token, Tout=Tout, name=name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\gen_script_ops.py\", line 129, in py_func\n    \"PyFunc\", input=input, token=token, Tout=Tout, name=name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3306, in create_op\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1669, in __init__\n    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access\n\nInvalidArgumentError (see above for traceback): TypeError: Invalid dimensions for image data\nTraceback (most recent call last):\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 157, in __call__\n    ret = func(*args)\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 27, in _visualize_images\n    output = _visualize_image(images[i], labels[i])\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 11, in _visualize_image\n    ax.imshow(image[::-1,...])\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\__init__.py\", line 1855, in inner\n    return func(ax, *args, **kwargs)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\axes\\_axes.py\", line 5487, in imshow\n    im.set_data(X)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 653, in set_data\n    raise TypeError(\"Invalid dimensions for image data\")\n\nTypeError: Invalid dimensions for image data\n\n\n\t [[Node: PyFunc = PyFunc[Tin=[DT_UINT8, DT_FLOAT], Tout=[DT_UINT8], token=\"pyfunc_0\", _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](PyFunc/input_0, PyFunc/input_1)]]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1329\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1330\u001b[1;33m       \u001b[1;32mreturn\u001b[0m \u001b[0mfn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1331\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mOpError\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[1;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n\u001b[0;32m   1314\u001b[0m       return self._call_tf_sessionrun(\n\u001b[1;32m-> 1315\u001b[1;33m           options, feed_dict, fetch_list, target_list, run_metadata)\n\u001b[0m\u001b[0;32m   1316\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_call_tf_sessionrun\u001b[1;34m(self, options, feed_dict, fetch_list, target_list, run_metadata)\u001b[0m\n\u001b[0;32m   1422\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_session\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moptions\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfeed_dict\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfetch_list\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtarget_list\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1423\u001b[1;33m             status, run_metadata)\n\u001b[0m\u001b[0;32m   1424\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\errors_impl.py\u001b[0m in \u001b[0;36m__exit__\u001b[1;34m(self, type_arg, value_arg, traceback_arg)\u001b[0m\n\u001b[0;32m    515\u001b[0m             \u001b[0mcompat\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mas_text\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mc_api\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mTF_Message\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 516\u001b[1;33m             c_api.TF_GetCode(self.status.status))\n\u001b[0m\u001b[0;32m    517\u001b[0m     \u001b[1;31m# Delete the underlying status object from memory otherwise it stays alive\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mInvalidArgumentError\u001b[0m: TypeError: Invalid dimensions for image data\nTraceback (most recent call last):\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 157, in __call__\n    ret = func(*args)\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 27, in _visualize_images\n    output = _visualize_image(images[i], labels[i])\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 11, in _visualize_image\n    ax.imshow(image[::-1,...])\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\__init__.py\", line 1855, in inner\n    return func(ax, *args, **kwargs)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\axes\\_axes.py\", line 5487, in imshow\n    im.set_data(X)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 653, in set_data\n    raise TypeError(\"Invalid dimensions for image data\")\n\nTypeError: Invalid dimensions for image data\n\n\n\t [[Node: PyFunc = PyFunc[Tin=[DT_UINT8, DT_FLOAT], Tout=[DT_UINT8], token=\"pyfunc_0\", _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](PyFunc/input_0, PyFunc/input_1)]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-8-70455aae5562>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[0ma\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvisualize_labeled_images\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mY\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;32mwith\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0msess\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m     \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msess\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0ma\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m    906\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    907\u001b[0m       result = self._run(None, fetches, feed_dict, options_ptr,\n\u001b[1;32m--> 908\u001b[1;33m                          run_metadata_ptr)\n\u001b[0m\u001b[0;32m    909\u001b[0m       \u001b[1;32mif\u001b[0m \u001b[0mrun_metadata\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    910\u001b[0m         \u001b[0mproto_data\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf_session\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mTF_GetBuffer\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrun_metadata_ptr\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run\u001b[1;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1141\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mfinal_fetches\u001b[0m \u001b[1;32mor\u001b[0m \u001b[0mfinal_targets\u001b[0m \u001b[1;32mor\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mhandle\u001b[0m \u001b[1;32mand\u001b[0m \u001b[0mfeed_dict_tensor\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1142\u001b[0m       results = self._do_run(handle, final_targets, final_fetches,\n\u001b[1;32m-> 1143\u001b[1;33m                              feed_dict_tensor, options, run_metadata)\n\u001b[0m\u001b[0;32m   1144\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1145\u001b[0m       \u001b[0mresults\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_run\u001b[1;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1322\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mhandle\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1323\u001b[0m       return self._do_call(_run_fn, feeds, fetches, targets, options,\n\u001b[1;32m-> 1324\u001b[1;33m                            run_metadata)\n\u001b[0m\u001b[0;32m   1325\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1326\u001b[0m       \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_do_call\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0m_prun_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhandle\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfeeds\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfetches\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1341\u001b[0m         \u001b[1;32mexcept\u001b[0m \u001b[0mKeyError\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1342\u001b[0m           \u001b[1;32mpass\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1343\u001b[1;33m       \u001b[1;32mraise\u001b[0m \u001b[0mtype\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0me\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnode_def\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mop\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmessage\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1344\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1345\u001b[0m   \u001b[1;32mdef\u001b[0m \u001b[0m_extend_graph\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mInvalidArgumentError\u001b[0m: TypeError: Invalid dimensions for image data\nTraceback (most recent call last):\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 157, in __call__\n    ret = func(*args)\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 27, in _visualize_images\n    output = _visualize_image(images[i], labels[i])\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 11, in _visualize_image\n    ax.imshow(image[::-1,...])\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\__init__.py\", line 1855, in inner\n    return func(ax, *args, **kwargs)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\axes\\_axes.py\", line 5487, in imshow\n    im.set_data(X)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 653, in set_data\n    raise TypeError(\"Invalid dimensions for image data\")\n\nTypeError: Invalid dimensions for image data\n\n\n\t [[Node: PyFunc = PyFunc[Tin=[DT_UINT8, DT_FLOAT], Tout=[DT_UINT8], token=\"pyfunc_0\", _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](PyFunc/input_0, PyFunc/input_1)]]\n\nCaused by op 'PyFunc', defined at:\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n    app.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 478, in start\n    self.io_loop.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 177, in start\n    super(ZMQIOLoop, self).start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 888, in start\n    handler_func(fd_obj, events)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n    self._handle_recv()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n    callback(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 283, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 233, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 399, in execute_request\n    user_expressions, allow_stdin)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 208, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 537, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2728, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2850, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2910, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-8-70455aae5562>\", line 1, in <module>\n    a = visualize_labeled_images(X, Y)\n  File \"<ipython-input-7-77ba72cfe590>\", line 31, in visualize_labeled_images\n    figs = tf.py_func(_visualize_images, [images, labels], tf.uint8)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 340, in py_func\n    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 241, in _internal_py_func\n    input=inp, token=token, Tout=Tout, name=name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\gen_script_ops.py\", line 129, in py_func\n    \"PyFunc\", input=input, token=token, Tout=Tout, name=name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3306, in create_op\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1669, in __init__\n    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access\n\nInvalidArgumentError (see above for traceback): TypeError: Invalid dimensions for image data\nTraceback (most recent call last):\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 157, in __call__\n    ret = func(*args)\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 27, in _visualize_images\n    output = _visualize_image(images[i], labels[i])\n\n  File \"<ipython-input-7-77ba72cfe590>\", line 11, in _visualize_image\n    ax.imshow(image[::-1,...])\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\__init__.py\", line 1855, in inner\n    return func(ax, *args, **kwargs)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\axes\\_axes.py\", line 5487, in imshow\n    im.set_data(X)\n\n  File \"C:\\Anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 653, in set_data\n    raise TypeError(\"Invalid dimensions for image data\")\n\nTypeError: Invalid dimensions for image data\n\n\n\t [[Node: PyFunc = PyFunc[Tin=[DT_UINT8, DT_FLOAT], Tout=[DT_UINT8], token=\"pyfunc_0\", _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](PyFunc/input_0, PyFunc/input_1)]]\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAOcAAADaCAYAAABdEFVTAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAMTQAADE0B0s6tTgAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDIuMi4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvhp/UCwAADClJREFUeJzt3W+IXQedxvHvs51u0nagS2lDmj2JkxfpYjb0RRiEUKkWhFjwXSpFDFjNiymCWxjckhduKWsRDMu80HYhKdEUohaTIP4b/xDFChshLiSS1JahltvJTdZkX9iVKWgJ/vbFOaPX25vpuXfOzP2Z83zgQM7J79w+yb1PzrmnZziKCMwsn78bdwAzG8zlNEvK5TRLyuU0S8rlNEvK5TRLyuU0S6pWOSV9SVJHUkjatcLc5yT9plo+31xMs/ape+Q8CbwfeONGA5IeBD4G3A/sBB6WtHfVCc1aqlY5I+LnEdF9l7FHgWMR8VZE/BH4CmVZzWwEEw2+1jbgpZ71DvDIoEFJs8Ds8vott9zyj5s3b24witn4Xb58+e2I2DDq/k2WE6D3Rl3dcChiDphbXi+KIrrddzswm/1tkfS/q9m/yau1i8BUz/p7qm1mNoImy3kC+ISkOyRtAD4FvNjg65u1St3/lfKcpC5QAKclvVZtn5c0DRARPwO+CVwAXgF+HBE/XJPUZi2gDD/P6e+cdjOSdDkiilH39x1CZkm5nGZJuZxmSbmcZkm5nGZJuZxmSbmcZkm5nGZJuZxmSbmcZkm5nGZJuZxmSbmcZkm5nGZJuZxmSbmcZkm5nGZJuZxmSbmcZkm5nGZJuZxmSbmcZkm5nGZJuZxmSbmcZkm5nGZJuZxmSdUup6Qdks5IWpB0VtLOATMbJR2TdEHSRUnfkXR3s5HN2mGYI+dh4EhE3AccAo4OmJkBJoH7I2IXcBV4ctUpzVqo7iMANwG7gePVplPAdklTA8ZvB26VNEFZVD8+zGwEdY+cW4ErEXEdIMrnBi4C2/rmDgO/B65RHjXvBJ7tfzFJs5K6y8vS0tKo+c1uWsOc1vY/yFMDZj5UzW0G7gXeBJ56xwtFzEVEsbxMTk4OEcOsHeqW8xJQVKeqSBLl0XSxb+5x4FsR8YeIeBv4GvBQU2HN2qRWOSPiGnAO2F9t2gd0IqLTN/o6sFcV4CPAxYaymrXKMKe1M8CMpAXgIHAAQNK8pOlq5mnK75kvU5bybuDfGktr1iIqr+2MV1EU0e36oq7dXCRdjohi1P19h5BZUi6nWVIup1lSLqdZUi6nWVIup1lSLqdZUi6nWVIup1lSLqdZUi6nWVIup1lSLqdZUi6nWVIup1lSLqdZUi6nWVIup1lSLqdZUi6nWVIup1lSLqdZUi6nWVIup1lSLqdZUi6nWVIup1lStcspaYekM5IWJJ2VtPMGcx+Q9EtJL0t6VdKe5uKatcfEELOHgSMRcUzSI8BR4K+KJ2kL8ALwcES8ImkjsLGxtGYtUuvIKWkTsBs4Xm06BWyXNNU3+mngeES8AlA9RPfNZqKatUvd09qtwJWIuA4Q5XMDF4FtfXM7gdsknZZ0XtKXJd3eXFyz9hjmglD/gzw1YOZW4IPAR4FpygfpPt0/JGlWUnd5WVpaGiKGWTvULecloJA0AVA9Un4r5dGz1xvA9yPid9VR9kXgff0vFhFzEVEsL5OTk6P/CcxuUrXKGRHXgHPA/mrTPqATEZ2+0a8DD0naUK1/GPhVAznNWmeY09oZYEbSAnAQOAAgaV7SNEBEnAG+C5yXdAG4B3iq2chm7aDy2s54FUUR3W533DHMGiXpckQUo+7vO4TMknI5zZJyOc2ScjnNknI5zZJyOc2ScjnNknI5zZJyOc2ScjnNknI5zZJyOc2ScjnNknI5zZJyOc2ScjnNknI5zZJyOc2ScjnNknI5zZJyOc2ScjnNknI5zZJyOc2ScjnNknI5zZJyOc2ScjnNkqpdTkk7JJ2RtCDprKSdK8zeI+mqpJPNxDRrn2GOnIeBIxFxH3AIOLrC7H8C86sJZtZ2tcopaROwGzhebToFbJc0NWD248BV4KVmIpq1U90j51bgSvUoeaJ8qOcisK13SNIWYJby4bo3JGlWUnd5WVpaGj652U1umNPa/qfsasDM88CTEbFi2yJiLiKK5WVycnKIGGbtMFFz7hJQSJqIiOuSRHk0Xeyb2wMcLX+bSeA2ST+KiL2NJTZriVpHzoi4BpwD9leb9gGdiOj0zd0VEVMRMQV8FviBi2k2mmFOa2eAGUkLlN8pDwBImpc0vRbhzNpM5bWd8SqKIrrd7rhjmDVK0uWIKEbd33cImSXlcpol5XKaJeVymiXlcpol5XKaJeVymiXlcpol5XKaJeVymiXlcpol5XKaJeVymiXlcpol5XKaJeVymiXlcpol5XKaJeVymiXlcpol5XKaJeVymiXlcpol5XKaJeVymiXlcpol5XKaJVW7nJJ2SDojaUHSWUk7B8w8KumcpIuSLkj6TLNxzdpjmCPnYeBIRNwHHAKODpjpAg9HxC7g/cATkh5YfUyz9qlVTkmbgN3A8WrTKWC7pKneuYj4r4j4bfXr/wNeBbY3FdasTeoeObcCVyLiOkCUzw1cBLbdaIfqtHcP8NMBvzcrqbu8LC2t+JR6s1Ya5rS2/0GeutGgpAL4NvB4RFx5xwtFzEVEsbxMTk4OEcOsHeqW8xJQSJoAkCTKo+li/6CkLcBp4JmIONFUULO2qVXOiLgGnAP2V5v2AZ2I6PTOSboX+AnwxYh4ocGcZq0zzGntDDAjaQE4CBwAkDQvabqa+XfK76FPSDpfLZ9sNLFZS6i8tjNeRVFEt9sddwyzRkm6HBHFqPv7DiGzpFxOs6RcTrOkXE6zpFxOs6RcTrOkXE6zpFxOs6RcTrOkXE6zpFxOs6RcTrOkXE6zpFxOs6RcTrOkXE6zpFxOs6RcTrOkXE6zpFxOs6RcTrOkXE6zpFxOs6RcTrOkXE6zpFxOs6RcTrOkapdT0g5JZyQtSDpbPRx30NznJP2mWj7fXFSzdhnmyHkYOBIR9wGHgKP9A5IeBD4G3A/sBB6WtLeJoGZtU6uckjYBu4Hj1aZTwHZJU32jjwLHIuKtiPgj8BXKsprZkCZqzm0FrkTEdYCICEmLlM/i7PTMbQNe6lnvAI/0v5ikWWC2Z9OfJP1P/djrYhJYGneIHs6zsmx5ADavZue65QTof5CnaswNnImIOWDuz0NSdzXPMVwL2TI5z8qy5YEy02r2r/ud8xJQSJqo/qOiPJou9s0tAlM96+8ZMGNmNdQqZ0RcA84B+6tN+4BORHT6Rk8An5B0h6QNwKeAFxvKatYqw1ytnQFmJC0AB4EDAJLmJU0DRMTPgG8CF4BXgB9HxA9rvPbcu4+su2yZnGdl2fLAKjMpov+rpJll4DuEzJJyOc2ScjnNklq3cma8N7dOJkmPSjon6aKkC5I+M848PbP3SLoq6eS480j6gKRfSnpZ0quS9owrj6SNko5V79VFSd+RdPca5fmSpI6kkLRrhbnRPtMRsS4L8FPgserXjwC/GDDzIPAycAewAfhvYO+YMz0AbK5+fSfwGvDAuPL0zJ4AvgqcHPPfzxbKO8HeW61vBP5hjHmeAE7yl4udzwOH1ijPg0BR/fl3rTAz0md6Td7UAQE3AW8CE9W6gN8CU31zzwH/2rP+acp7dceWacB+3wP2jzMP8HHgWeCxtSrnEO/ZM8AziT5DTwDzwN9T3gH3DeBf1jjbSuUc+TO9Xqe177g3l/LOoW19c9uAN3rWOwNm1jvTn1WnUXso/wUfSx5JWyjvSz64BhmGzkP500e3STot6bykL0u6fYx5DgO/B64BVynPdp5dgzx1jfyZXs8LQo3dm9ugupmQVADfBh6PiCtjzPM88GRErMdN3nXy3Ap8EPgoME1ZhqfHmOdD1dxm4F7Ko+1Ta5SnrpE+0+tVzoz35tbNtHy0Ok15+nZizHn2AEcldYD/oPyZ2R+NMc8bwPcj4nfVUe1F4H1jzPM48K2I+ENEvA18DXhoDfLUNfJnel3KGQnvza2bSdK9wE+AL0bEC2uRZZg8EXFXRExFxBTwWeAHEdH4D7QP8Z59HXioer8APgz8aox5Xgf2qgJ8BLjYdJ4hjP6ZXusv8j1fhP8J+AWwQHnF6p+r7fPAdM/cU5R/wa8DXxh3JsrTyLeA8z3LJ8f5d9Qz/xhre7W27nv2JOW91BcoL8DcOcb36y7Kq7W/prxKegK4a43yPAd0geuUF6dea/Iz7XtrzZLyHUJmSbmcZkm5nGZJuZxmSbmcZkm5nGZJuZxmSbmcZkn9P/xcqkPumHLjAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 240x240 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "a = visualize_labeled_images(X, Y)\n",
    "with tf.Session() as sess:\n",
    "    print(sess.run(a))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  },
  "latex_envs": {
   "LaTeX_envs_menu_present": true,
   "autoclose": false,
   "autocomplete": true,
   "bibliofile": "biblio.bib",
   "cite_by": "apalike",
   "current_citInitial": 1,
   "eqLabelWithNumbers": true,
   "eqNumInitial": 1,
   "hotkeys": {
    "equation": "Ctrl-E",
    "itemize": "Ctrl-I"
   },
   "labels_anchors": false,
   "latex_user_defs": false,
   "report_style_numbering": false,
   "user_envs_cfg": false
  },
  "toc": {
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
